CREATE TYPE event_types AS ENUM ('CONCERT', 'SEMINAR', 'MEETUP', 'WEBINAR', 'FESTIVAL', 'EXHIBITION');

CREATE TABLE Events (
    ID             BIGSERIAL PRIMARY KEY NOT NULL,
    NAME           TEXT NOT NULL ,
    DESCRIPTION    TEXT NOT NULL ,
    LOCATION       TEXT NOT NULL ,
    START_DATE     TIMESTAMP NOT NULL ,
    END_DATE       TIMESTAMP NOT NULL ,
    OWNER          TEXT NOT NULL ,
    CONTACT        TEXT NOT NULL ,
    TYPE           TEXT NOT NULL ,
    CATEGORY       event_types NOT NULL ,
    CAPACITY       INTEGER NOT NULL ,
    IDENTIFICATION TEXT NOT NULL
);